import { Product } from './types';

export const products: Product[] = [
  {
    id: 1,
    name: "Orange Sticks",
    image: "/products/WhatsApp Image 2026-04-22 at 3.00.13 PM.jpeg",
    price: 300,
    rating: 4.8,
    reviews: 245,
    description: "Orange Sticks are a bold and flavorful snack designed for those who love spicy and tangy tastes. These crunchy sticks are coated with a special blend of spices that enhance every bite. Perfect for evening cravings, parties, or casual snacking, they bring excitement to every moment. Their crispy texture combined with rich seasoning makes them highly addictive and enjoyable. MS Crunch ensures freshness and quality in every pack, making them a favorite among spice lovers. They are not just a snack but a flavorful experience that fits perfectly into today’s fast and active lifestyle.",
    ingredients: ["Wheat flour", "Chili powder", "Spices", "Salt", "Vegetable oil"],
    weight: "200g",
    featured: true,
  },
  {
    id: 2,
    name: "Salt Slanty",
    image: "/products/WhatsApp Image 2026-04-22 at 3.00.14 PM.jpeg",
    price: 300,
    rating: 4.7,
    reviews: 189,
    description: "Salt Slanty is a simple yet satisfying snack designed for those who prefer light and classic flavors. Its crisp texture and mild salt seasoning make it perfect for everyday enjoyment. Whether at home, school, or office breaks, it provides a quick and enjoyable snacking experience. MS Crunch ensures high quality and freshness in every pack, making it a reliable choice for all age groups",
    ingredients: ["Wheat flour", "Salt", "Vegetable oil"],
    weight: "150g",
    featured: true,
  },
  {
    id: 3,
    name: "Chatpata Mix Nimko",
    image: "/products/WhatsApp Image 2026-04-22 at 3.00.48 PM.jpeg",
    price: 300,
    rating: 4.9,
    reviews: 312,
    description: "Chatpata Mix Nimko is the perfect companion for your daily snacking moments, whether you’re enjoying evening tea or spending time with family. This flavorful blend combines a variety of crunchy elements, creating a balanced mix of spice, tanginess, and texture. Designed for those who love traditional desi snacks with a modern twist, it delivers satisfaction in every bite. Its rich taste and crispy texture make it ideal for gatherings, lunchboxes, or quick cravings during a busy day. With MS Crunch, this classic snack is elevated to match today’s lifestyle convenient, delicious, and full of flavor that keeps you coming back for more.",
    ingredients: ["Gram flour (besan)", "Peanuts", "Lentils", "Wheat flour", "Spices", "Salt", "Edible oil"],
    weight: "200g",
    featured: true,
  },
  {
    id: 4,
    name: "Spicy Potato Chips",
    image: "/products/WhatsApp Image 2026-04-22 at 3.00.51 PM.jpeg",
    price: 300,
    rating: 4.6,
    reviews: 156,
    description: "Spicy Potato Chips are crafted for those who enjoy bold flavors and an exciting snacking experience. Made from carefully selected potatoes, these chips are sliced thin and fried to achieve the perfect crunch. Coated with a rich blend of spices, they deliver a fiery taste that complements modern lifestyles where quick and flavorful snacks are essential. Whether you’re relaxing, studying, or hanging out with friends, these chips add a punch of spice to your moments. MS Crunch brings you a snack that not only satisfies cravings but also energizes your mood with every crispy bite.",
    ingredients: ["Fresh potatoes", "Chili powder", "Salt", "Spices", "Vegetable oil"],
    weight: "180g",
    featured: false,
  },
  {
    id: 5,
    name: "Crispy Potato Chips",
    image: "/products/WhatsApp Image 2026-04-22 at 3.00.52 PM.jpeg",
    price: 300,
    rating: 4.8,
    reviews: 267,
    description: "Crispy Potato Chips are a timeless snack loved for their simple yet satisfying taste. Made from fresh, high-quality potatoes, they are sliced thin and fried to golden perfection. Lightly salted to maintain a classic flavor, these chips are perfect for all age groups. Whether you are at home, in school breaks, or enjoying a movie night, they deliver consistent crunch and freshness. MS Crunch ensures premium quality in every pack, making it a reliable choice for everyday snacking. Their balanced taste fits perfectly into modern lifestyles where people prefer quick, light, and enjoyable snacks without overwhelming spices.",
    ingredients: ["Fresh potatoes", "Salt", "Vegetable oil"],
    weight: "170g",
    featured: true,
  },
  {
    id: 6,
    name: "Classic Chatpata Nimko",
    image: "/products/WhatsApp Image 2026-04-22 at 3.00.53 PM.jpeg",
    price: 300,
    rating: 4.8,
    reviews: 198,
    description: "Classic Chatpata Nimko is a traditional snack that delivers an authentic desi taste with a modern touch. It combines crispy elements with a perfect blend of spices, creating a tangy and flavorful experience. Ideal for tea-time, family gatherings, or daily snacking.",
    ingredients: ["Gram flour", "Lentils", "Peanuts", "Wheat flour", "Spices", "Salt", "Vegetable oil"],
    weight: "190g",
    featured: false,
  },
  {
    id: 7,
    name: "Royal Mix Nimko",
    image: "/products/WhatsApp Image 2026-04-22 at 3.00.54 PM.jpeg",
    price: 300,
    rating: 4.9,
    reviews: 134,
    description: "Royal Mix Nimko is a premium snack blend crafted for special occasions and refined taste preferences. It includes a rich combination of crunchy elements like nuts, lentils, and spices that create a luxurious snacking experience. Designed for gatherings and hospitality.",
    ingredients: ["Gram flour", "Cashews", "Peanuts", "Lentils", "Spices", "Salt", "Vegetable oil"],
    weight: "220g",
    featured: true,
  },
  {
    id: 8,
    name: "Chilli Chips",
    image: "/products/WhatsApp Image 2026-04-22 at 3.00.54 PM (1).jpeg",
    price: 300,
    rating: 4.7,
    reviews: 201,
    description: "Chilli Chips are small, crispy bites packed with intense spicy flavor. Designed for spice lovers, they deliver a bold kick in every crunch. Their compact size makes them perfect for quick snacking anytime, anywhere.",
    ingredients: ["Potatoes", "Chili powder", "Spices", "Salt", "Vegetable oil"],
    weight: "160g",
    featured: false,
  },
  {
    id: 9,
    name: "Spicy Stix",
    image: "/products/WhatsApp Image 2026-04-22 at 3.00.55 PM.jpeg",
    price: 300,
    rating: 4.8,
    reviews: 223,
    description: "Spicy Stix are crunchy stick-shaped snacks designed for those who love bold and spicy flavors. Each stick is coated with a special spice mix that enhances its taste and aroma. Perfect for casual snacking, parties, or tea-time enjoyment.",
    ingredients: ["Wheat flour", "Chili powder", "Spices", "Salt", "Vegetable oil"],
    weight: "175g",
    featured: false,
  },
];

export const testimonials = [
  {
    id: 1,
    name: "Ali Raza",
    image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop",
    rating: 5,
    text: "The taste is really amazing and fresh. I loved the perfect balance of spice and crunch, it feels very satisfying. MS Crunch is the best!"
  },
  {
    id: 2,
    name: "Maham Ali",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop",
    rating: 5,
    text: "Absolutely loved it! Perfect spicy flavor with amazing crunch. One of the best chips I have tried so far. Highly recommended!"
  },
  {
    id: 3,
    name: "Usman Tariq",
    image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop",
    rating: 5,
    text: "Honestly one of the best nimko mixes I have tried. Fresh, crunchy and full of desi flavor in every bite. Worth every penny!"
  },
  {
    id: 4,
    name: "Shahzaib Ali",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop",
    rating: 5,
    text: "Absolutely amazing snack! Perfect spice level and very addictive. I really enjoyed it a lot and will definitely buy again!"
  },
];
